/*
 * This file is part of JAtm - The Jupiter Ace tape manager.
 *
 * JAtm is a tool to manage Jupiter Ace tape files in several formats.
 * Copyright (C) 2015  Ricardo Fernandes Lopes
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package JatmUI;

import Jatm.JaTape;
import javax.swing.ImageIcon;

/**
 *
 * @author Ricardo
 */
public class EditHeaderDialog extends javax.swing.JDialog {
    // ------------------ STATIC --------------------
    private static final ImageIcon dictIcon, bytIcon;
    static{
        dictIcon = new ImageIcon(EditHeaderDialog.class.getResource("resources/book.png"));
        bytIcon  = new ImageIcon(EditHeaderDialog.class.getResource("resources/cog.png"));
    }    
    // ----------------------------------------------
    
    private final JaTape tape;

    private Boolean dict; // track selected file mode

    /**
     * Creates new form HeaderEditDialog
     * @param parent
     * @param modal
     * @param t
     */
    public EditHeaderDialog(java.awt.Frame parent, boolean modal, JaTape t) {
        super(parent, modal);
              
        initComponents();

        tape = t;
        this.setTitle("File Header [" + tape.getFilename() + "]");   

        filenameField.setText(tape.getFilename());
        lengthField.setText(String.valueOf(tape.getParameter(JaTape.LENGTH)));
        addressField.setText(String.valueOf(tape.getParameter(JaTape.ADDRESS)));
        currWrdField.setText(String.valueOf(tape.getParameter(JaTape.CURR_WRD)));
        currentField.setText(String.valueOf(tape.getParameter(JaTape.CURRENT)));
        contextField.setText(String.valueOf(tape.getParameter(JaTape.CONTEXT)));
        voclnkField.setText(String.valueOf(tape.getParameter(JaTape.VOCLNK)));
        stkbotField.setText(String.valueOf(tape.getParameter(JaTape.STKBOT)));
        dict = tape.isDict();
        if(tape.isDict()) {
            fileTypeLabel.setIcon(dictIcon);
        } else {
            fileTypeLabel.setIcon(bytIcon);
        }
    }
    
    // Save Data from Dialog fields into Tape
    private void modifyTape() {
        tape.setFilename(filenameField.getText());

        if( lengthField.getText().matches("\\d+") ) {
            tape.setParameter(JaTape.LENGTH, Integer.parseInt(lengthField.getText()));
        }
        if( addressField.getText().matches("\\d+") ) {
            tape.setParameter(JaTape.ADDRESS, Integer.parseInt(addressField.getText()));
        }
        if( currWrdField.getText().matches("\\d+") ) {
            tape.setParameter(JaTape.CURR_WRD, Integer.parseInt(currWrdField.getText()));
        }
        if( currentField.getText().matches("\\d+") ) {
            tape.setParameter(JaTape.CURRENT, Integer.parseInt(currentField.getText()));
        }
        if( contextField.getText().matches("\\d+") ) {
            tape.setParameter(JaTape.CONTEXT, Integer.parseInt(contextField.getText()));
        }
        if( voclnkField.getText().matches("\\d+") ) {
            tape.setParameter(JaTape.VOCLNK, Integer.parseInt(voclnkField.getText()));
        }
        if( stkbotField.getText().matches("\\d+") ) {
            tape.setParameter(JaTape.STKBOT, Integer.parseInt(stkbotField.getText()));
        }

        if(dict) {
            tape.setType(JaTape.DICT_FILE);
        } else {
            tape.setType(JaTape.BYT_FILE);
        }
        tape.fixHeaderCrc();
        tape.fixDataCrc();  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileTypeGroup = new javax.swing.ButtonGroup();
        attrPanel = new javax.swing.JPanel();
        addressLabel = new javax.swing.JLabel();
        addressField = new javax.swing.JTextField();
        currWrdLabel = new javax.swing.JLabel();
        currWrdField = new javax.swing.JTextField();
        currentLabel = new javax.swing.JLabel();
        currentField = new javax.swing.JTextField();
        contextLabel = new javax.swing.JLabel();
        contextField = new javax.swing.JTextField();
        voclnkLabel = new javax.swing.JLabel();
        voclnkField = new javax.swing.JTextField();
        stkbotLabel = new javax.swing.JLabel();
        stkbotField = new javax.swing.JTextField();
        lengthLabel = new javax.swing.JLabel();
        lengthField = new javax.swing.JTextField();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        filenameField = new javax.swing.JTextField();
        fileTypeLabel = new javax.swing.JLabel();
        makeBytButtom = new javax.swing.JButton();
        makeDictButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Attributes");
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(252, 246));
        setModal(true);

        attrPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Attributes"));
        attrPanel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        addressLabel.setText("Address");

        addressField.setColumns(5);
        addressField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        addressField.setMinimumSize(new java.awt.Dimension(42, 20));

        currWrdLabel.setText("Curr Word");

        currWrdField.setColumns(5);
        currWrdField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        currWrdField.setMinimumSize(new java.awt.Dimension(42, 20));

        currentLabel.setText("CURRENT");

        currentField.setColumns(5);
        currentField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        currentField.setMinimumSize(new java.awt.Dimension(42, 20));

        contextLabel.setText("CONTEXT");

        contextField.setColumns(5);
        contextField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        contextField.setMinimumSize(new java.awt.Dimension(42, 20));

        voclnkLabel.setText("VOCLNK");

        voclnkField.setColumns(5);
        voclnkField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        voclnkField.setMinimumSize(new java.awt.Dimension(42, 20));

        stkbotLabel.setText("STKBOT");

        stkbotField.setColumns(5);
        stkbotField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        stkbotField.setMinimumSize(new java.awt.Dimension(42, 20));

        lengthLabel.setText("Length");

        lengthField.setColumns(5);
        lengthField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        lengthField.setMaximumSize(new java.awt.Dimension(42, 20));
        lengthField.setMinimumSize(new java.awt.Dimension(42, 20));

        javax.swing.GroupLayout attrPanelLayout = new javax.swing.GroupLayout(attrPanel);
        attrPanel.setLayout(attrPanelLayout);
        attrPanelLayout.setHorizontalGroup(
            attrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(attrPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(attrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(attrPanelLayout.createSequentialGroup()
                        .addComponent(addressLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(attrPanelLayout.createSequentialGroup()
                        .addComponent(lengthLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lengthField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(attrPanelLayout.createSequentialGroup()
                        .addComponent(currWrdLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(currWrdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(attrPanelLayout.createSequentialGroup()
                        .addComponent(currentLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(currentField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(attrPanelLayout.createSequentialGroup()
                        .addComponent(contextLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(contextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(attrPanelLayout.createSequentialGroup()
                        .addComponent(voclnkLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(voclnkField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(attrPanelLayout.createSequentialGroup()
                        .addComponent(stkbotLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(stkbotField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        attrPanelLayout.setVerticalGroup(
            attrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(attrPanelLayout.createSequentialGroup()
                .addGroup(attrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressLabel)
                    .addComponent(addressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(attrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lengthLabel)
                    .addComponent(lengthField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(attrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currWrdLabel)
                    .addComponent(currWrdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(attrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currentLabel)
                    .addComponent(currentField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(attrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contextLabel)
                    .addComponent(contextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(attrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(voclnkLabel)
                    .addComponent(voclnkField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(attrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stkbotLabel)
                    .addComponent(stkbotField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        okButton.setMnemonic('O');
        okButton.setText("Ok");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setMnemonic('C');
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        fileTypeLabel.setMaximumSize(new java.awt.Dimension(16, 16));
        fileTypeLabel.setMinimumSize(new java.awt.Dimension(16, 16));
        fileTypeLabel.setPreferredSize(new java.awt.Dimension(16, 16));

        makeBytButtom.setMnemonic('B');
        makeBytButtom.setText("Make Byt");
        makeBytButtom.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        makeBytButtom.setMaximumSize(new java.awt.Dimension(78, 23));
        makeBytButtom.setMinimumSize(new java.awt.Dimension(78, 23));
        makeBytButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeBytButtomActionPerformed(evt);
            }
        });

        makeDictButton.setMnemonic('D');
        makeDictButton.setText("Make Dict");
        makeDictButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        makeDictButton.setMaximumSize(new java.awt.Dimension(78, 23));
        makeDictButton.setMinimumSize(new java.awt.Dimension(78, 23));
        makeDictButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeDictButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fileTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(filenameField, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(attrPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(makeBytButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(makeDictButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(fileTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9))
                    .addComponent(filenameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(makeDictButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(makeBytButtom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(okButton)
                        .addGap(18, 18, 18)
                        .addComponent(cancelButton))
                    .addComponent(attrPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        modifyTape();
        dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void makeDictButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeDictButtonActionPerformed
        dict = true;
        fileTypeLabel.setIcon(dictIcon);
        currWrdField.setText(String.valueOf(tape.getParameter(JaTape.CURR_WRD)));
        addressField.setText("15441"); // 0x3C51
        currentField.setText("15436"); // 0x3C4C
        contextField.setText("15436"); // 0x3C4C
        voclnkField.setText("15439");  // 0x3C4F
        stkbotField.setText(String.valueOf(tape.getParameter(JaTape.LENGTH)+15441));  // = 15441 + Length
    }//GEN-LAST:event_makeDictButtonActionPerformed

    private void makeBytButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeBytButtomActionPerformed
        dict = false;
        fileTypeLabel.setIcon(bytIcon);
        currWrdField.setText("8224"); // 0x2020
        currentField.setText("8224"); // 0x2020
        contextField.setText("8224"); // 0x2020
        voclnkField.setText("8224");  // 0x2020
        stkbotField.setText("8224");  // 0x2020
    }//GEN-LAST:event_makeBytButtomActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressField;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JPanel attrPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField contextField;
    private javax.swing.JLabel contextLabel;
    private javax.swing.JTextField currWrdField;
    private javax.swing.JLabel currWrdLabel;
    private javax.swing.JTextField currentField;
    private javax.swing.JLabel currentLabel;
    private javax.swing.ButtonGroup fileTypeGroup;
    private javax.swing.JLabel fileTypeLabel;
    private javax.swing.JTextField filenameField;
    private javax.swing.JTextField lengthField;
    private javax.swing.JLabel lengthLabel;
    private javax.swing.JButton makeBytButtom;
    private javax.swing.JButton makeDictButton;
    private javax.swing.JButton okButton;
    private javax.swing.JTextField stkbotField;
    private javax.swing.JLabel stkbotLabel;
    private javax.swing.JTextField voclnkField;
    private javax.swing.JLabel voclnkLabel;
    // End of variables declaration//GEN-END:variables
}
