/*
 * This file is part of JAtm - The Jupiter Ace tape manager.
 *
 * JAtm is a tool to manage Jupiter Ace tape files in several formats.
 * Copyright (C) 2015  Ricardo Fernandes Lopes
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package JatmUI;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author Ricardo
 */
public class ViewCharacterSetDialog extends javax.swing.JDialog {

    // Character Set Panel Dimensions
    private static final int PANEL_MARGIN = 10;
    private static final int GRID_GAP = 2;
    private static final int GRID_SIZE = 8 + GRID_GAP;
    private static final int PANEL_SIZE = 16*8 + 15*GRID_GAP + 2*PANEL_MARGIN;
    
    int offset, nChars;
    byte[] currentCharBytes;
    CharacterSet currentCharSet; // Selected file Char Set
    CharacterSet userCharSet; // Current User Defined Character Set

    /**
     * Creates new form NewJDialog
     * @param parent
     * @param modal
     * @param data
     * @param start
     * @param userCS
     * @param filename
     */
    public ViewCharacterSetDialog(java.awt.Frame parent, boolean modal,
            byte[] data, int start, CharacterSet userCS, String filename) {
        super(parent, modal);
        
        this.setTitle("Characters [" + filename + "]");

        initComponents();
        
        charPanel.setSize(PANEL_SIZE, PANEL_SIZE);
        offset = start; // first character index
        nChars = data.length >> 3; // number of characters in data
        currentCharBytes = new byte[1024];
        currentCharBytes = data.clone();
        currentCharSet = new CharacterSet();
        currentCharSet.load(data, start); // Set current Character Set
        userCharSet = userCS; // User Char Set        
    }

    @Override 
    public void paint(Graphics g) {
        super.paint(g);

        Graphics charPanelGraph = charPanel.getGraphics(); 
        int c;
        for(int y = 0; y < 16; y++) { // 16 char rows
            for(int x = 0; x < 16; x++) { // 16 char columns
                c = x + y*16; // character index

                if ((c < 128 && c >= offset && c < offset + nChars) ||
                    (c > 127 && c >= offset + 128 && c < offset + nChars + 128)) { // Border colour
                    charPanelGraph.setColor(new Color(0, 0, 255)); // UDC  
                } else {
                    charPanelGraph.setColor(new Color(128,128,128)); // ROM char                  
                }
                // draw char border
                charPanelGraph.fillRect( PANEL_MARGIN + GRID_SIZE*x-1,
                                         PANEL_MARGIN + GRID_SIZE*y-1,
                                         10, 10);                
                // draw char face
                charPanelGraph.drawImage(currentCharSet.getImage(x + y*16),
                        PANEL_MARGIN + GRID_SIZE*x,
                        PANEL_MARGIN + GRID_SIZE*y,
                        null);
            }
        } 
    }   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loadButton = new javax.swing.JButton();
        discardButton = new javax.swing.JButton();
        charPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        offsetSpinner = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Character Set");
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(200, 280));
        setPreferredSize(new java.awt.Dimension(200, 250));

        loadButton.setMnemonic('L');
        loadButton.setText("Load");
        loadButton.setMaximumSize(new java.awt.Dimension(200, 23));
        loadButton.setMinimumSize(new java.awt.Dimension(78, 23));
        loadButton.setPreferredSize(new java.awt.Dimension(78, 23));
        loadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButtonActionPerformed(evt);
            }
        });

        discardButton.setMnemonic('C');
        discardButton.setText("Close");
        discardButton.setMaximumSize(new java.awt.Dimension(200, 23));
        discardButton.setMinimumSize(new java.awt.Dimension(78, 23));
        discardButton.setPreferredSize(new java.awt.Dimension(78, 23));
        discardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discardButtonActionPerformed(evt);
            }
        });

        charPanel.setBackground(new java.awt.Color(0, 0, 0));
        charPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        charPanel.setDoubleBuffered(false);
        charPanel.setMaximumSize(new java.awt.Dimension(178, 178));
        charPanel.setMinimumSize(new java.awt.Dimension(178, 178));
        charPanel.setPreferredSize(new java.awt.Dimension(178, 178));

        javax.swing.GroupLayout charPanelLayout = new javax.swing.GroupLayout(charPanel);
        charPanel.setLayout(charPanelLayout);
        charPanelLayout.setHorizontalGroup(
            charPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        charPanelLayout.setVerticalGroup(
            charPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 172, Short.MAX_VALUE)
        );

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Offset");

        offsetSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 127, 1));
        offsetSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                offsetChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(charPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(discardButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(loadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(offsetSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(charPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loadButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(offsetSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(discardButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButtonActionPerformed
        userCharSet.load(currentCharBytes,offset);
        this.setVisible(false);
    }//GEN-LAST:event_loadButtonActionPerformed

    private void discardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discardButtonActionPerformed
        dispose();
    }//GEN-LAST:event_discardButtonActionPerformed

    private void offsetChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_offsetChanged
        offset = (Integer) offsetSpinner.getValue();
        currentCharSet.load(currentCharBytes, offset); // update Character Set
        repaint();
    }//GEN-LAST:event_offsetChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel charPanel;
    private javax.swing.JButton discardButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton loadButton;
    private javax.swing.JSpinner offsetSpinner;
    // End of variables declaration//GEN-END:variables
}
