/*
 * This file is part of JAtm - The Jupiter Ace tape manager.
 *
 * JAtm is a tool to manage Jupiter Ace tape files in several formats.
 * Copyright (C) 2015  Ricardo Fernandes Lopes
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package JatmUI;

import Jatm.JaDisasm;
import Jatm.JaTape;

public class ViewCodeDialog extends javax.swing.JDialog {

    private final JaTape tape;
    private final JaDisasm forthDisasm;

    /**
     * Creates new form DisasmDialog
     * @param parent
     * @param modal
     * @param t
     */
    public ViewCodeDialog(java.awt.Frame parent, boolean modal, JaTape t) {
        super(parent, modal);
        tape = t;
        forthDisasm = new JaDisasm(t);
        initComponents();
        this.setTitle("Code [" + tape.getFilename() + "]" );
        printContents();
        printCode();
    }

    public final void printContents() {
        // Write File Info
        if (tape.isDict()) {
            ContentsTextArea.append("Dict: ");
        } else {
            ContentsTextArea.append("Byt: ");
        }
        ContentsTextArea.append(tape.getFilename() + " ( "
            + tape.getParameter(JaTape.LENGTH) + " bytes "
            + String.format("at %04Xh )", tape.getParameter(JaTape.ADDRESS)) + "\n");
        if (tape.isDict()) {
            ContentsTextArea.append("----- " + forthDisasm.vocSize() + " words -----\n");
            ContentsTextArea.append(forthDisasm.vlist());
        }
        ContentsTextArea.setEditable(false);  // Avoid user editing
        ContentsTextArea.setCaretPosition(0); // move to top of text  
    }
    
    public final void printCode() {    
        // Disassemble
        if (tape.isDict()) {
            CodeTextArea.append(forthDisasm.decode());
        } else {
            CodeTextArea.append("; Jupiter Ace Binary File \""
                    + tape.getFilename() + "\"\n\n");
            CodeTextArea.append("        .org    "
                    + String.format("%04Xh", tape.getParameter(JaTape.ADDRESS)) + "\n");
            CodeTextArea.append("*** Z80 Disassembler not implemented ***\n");
        }

        
        CodeTextArea.setEditable(false);  // Avoid user editing
        CodeTextArea.setCaretPosition(0); // move to top of text         
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabbedPane = new javax.swing.JTabbedPane();
        ContentsScrollPane = new javax.swing.JScrollPane();
        ContentsTextArea = new javax.swing.JTextArea();
        CodeScrollPane = new javax.swing.JScrollPane();
        CodeTextArea = new javax.swing.JTextArea();
        CloseButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Code View");
        setLocationByPlatform(true);

        ContentsTextArea.setColumns(20);
        ContentsTextArea.setRows(5);
        ContentsScrollPane.setViewportView(ContentsTextArea);

        TabbedPane.addTab("Vocabulary", ContentsScrollPane);

        CodeTextArea.setColumns(20);
        CodeTextArea.setRows(5);
        CodeScrollPane.setViewportView(CodeTextArea);

        TabbedPane.addTab("Code", CodeScrollPane);

        CloseButton.setMnemonic('C');
        CloseButton.setText("Close");
        CloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CloseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CloseButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseButtonActionPerformed
        dispose();
    }//GEN-LAST:event_CloseButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CloseButton;
    private javax.swing.JScrollPane CodeScrollPane;
    private javax.swing.JTextArea CodeTextArea;
    private javax.swing.JScrollPane ContentsScrollPane;
    private javax.swing.JTextArea ContentsTextArea;
    private javax.swing.JTabbedPane TabbedPane;
    // End of variables declaration//GEN-END:variables
}
