/*
 * This file is part of JAtm - The Jupiter Ace tape manager.
 *
 * JAtm is a tool to manage Jupiter Ace tape files in several formats.
 * Copyright (C) 2015  Ricardo Fernandes Lopes
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package JatmUI;

import Jatm.JatmWaveSave;

public class WavSaveParamsDialog extends javax.swing.JDialog {

    /**
     * Creates new form SaveWavParamsDialog
     * @param parent
     * @param modal
     */
    public WavSaveParamsDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initValues();
    }

    // Populate dialog with current values
    private void initValues() {
        // Get Sample Rate: 22050, 44100, 48000 Hz
        switch(JatmWaveSave.getSampleRate()) {
            case 22050:
                sampleRateComboBox.setSelectedIndex(0); // 22050
                break;
            case 48000:
                sampleRateComboBox.setSelectedIndex(2); // 48000
                break;
            default: sampleRateComboBox.setSelectedIndex(1); // 44100
        }
        // Get Sample Size: 8, 16, 24, 32 bits
        switch(JatmWaveSave.getBits()) {
            case 8:
                bitsComboBox.setSelectedIndex(0); // 8 bits
                break;
            case 24:
                bitsComboBox.setSelectedIndex(2); // 24 bits
                break;
            case 32:
                bitsComboBox.setSelectedIndex(3); // 32 bits
                break;
            default: bitsComboBox.setSelectedIndex(1); // 16 bits
        }  
        // Get Channels: mono or stereo
        stereoRadioButton.setSelected(JatmWaveSave.isStereo());
        // Get Volume: 0-100%
        volumeSlider.setValue(JatmWaveSave.getLevel());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        channelsRateGroup = new javax.swing.ButtonGroup();
        volumePanel = new javax.swing.JPanel();
        volumeSlider = new javax.swing.JSlider();
        channelPanel = new javax.swing.JPanel();
        monoRadioButton = new javax.swing.JRadioButton();
        stereoRadioButton = new javax.swing.JRadioButton();
        defaultButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        sampleRateComboBox = new javax.swing.JComboBox();
        bitsComboBox = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Wav Save Parameters");
        setLocationByPlatform(true);

        volumePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Volume"));

        volumeSlider.setMajorTickSpacing(20);
        volumeSlider.setMinorTickSpacing(10);
        volumeSlider.setOrientation(javax.swing.JSlider.VERTICAL);
        volumeSlider.setPaintLabels(true);
        volumeSlider.setPaintTicks(true);
        volumeSlider.setSnapToTicks(true);
        volumeSlider.setToolTipText("");
        volumeSlider.setValue(90);

        javax.swing.GroupLayout volumePanelLayout = new javax.swing.GroupLayout(volumePanel);
        volumePanel.setLayout(volumePanelLayout);
        volumePanelLayout.setHorizontalGroup(
            volumePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(volumePanelLayout.createSequentialGroup()
                .addComponent(volumeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        volumePanelLayout.setVerticalGroup(
            volumePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(volumeSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        channelPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Channels"));
        channelPanel.setToolTipText("");

        channelsRateGroup.add(monoRadioButton);
        monoRadioButton.setSelected(true);
        monoRadioButton.setText("Mono");

        channelsRateGroup.add(stereoRadioButton);
        stereoRadioButton.setText("Stereo");

        javax.swing.GroupLayout channelPanelLayout = new javax.swing.GroupLayout(channelPanel);
        channelPanel.setLayout(channelPanelLayout);
        channelPanelLayout.setHorizontalGroup(
            channelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(monoRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(stereoRadioButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        channelPanelLayout.setVerticalGroup(
            channelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(channelPanelLayout.createSequentialGroup()
                .addComponent(monoRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(stereoRadioButton))
        );

        defaultButton.setText("Default");
        defaultButton.setMaximumSize(new java.awt.Dimension(57, 23));
        defaultButton.setMinimumSize(new java.awt.Dimension(57, 23));
        defaultButton.setPreferredSize(new java.awt.Dimension(57, 23));
        defaultButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defaultButtonActionPerformed(evt);
            }
        });

        okButton.setMnemonic('S');
        okButton.setText("Ok");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setMnemonic('C');
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        sampleRateComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "22050 Hz", "44100 Hz", "48000 Hz" }));
        sampleRateComboBox.setToolTipText("Sampling Rate");

        bitsComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "8 bits", "16 bits", "24 bits", "32 bits" }));
        bitsComboBox.setToolTipText("Sample Size");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(volumePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(sampleRateComboBox, 0, 77, Short.MAX_VALUE)
                    .addComponent(defaultButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bitsComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(okButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(channelPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(channelPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sampleRateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bitsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(defaultButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(okButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelButton))
                    .addComponent(volumePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // Set Sample Rate
        switch (sampleRateComboBox.getSelectedIndex()) {
            case 0:
                JatmWaveSave.setSampleRate(22050);
                break;
            case 2:
                JatmWaveSave.setSampleRate(48000);
                break;        
            default:
                JatmWaveSave.setSampleRate(44100);                
        }
        // Set Sample Size in Bits
        switch (bitsComboBox.getSelectedIndex()) {
            case 0:
                JatmWaveSave.setBits(8);
                break;
            case 2:
                JatmWaveSave.setBits(24);
                break;
            case 3:
                JatmWaveSave.setBits(32);
                break;        
            default:
                JatmWaveSave.setBits(16);                
        }
        JatmWaveSave.setStereo(stereoRadioButton.isSelected()); // Set Channel Usage
        JatmWaveSave.setLevel(volumeSlider.getValue()); // Set Volume: 0-100%

        this.setVisible(false);
    }//GEN-LAST:event_okButtonActionPerformed

    private void defaultButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defaultButtonActionPerformed
        sampleRateComboBox.setSelectedIndex(1); // Sample Rate 44100 Hz
        monoRadioButton.setSelected(true);      // Mono
        bitsComboBox.setSelectedIndex(1);       // 16 bits
        volumeSlider.setValue(90);              // Volume = 90%
    }//GEN-LAST:event_defaultButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox bitsComboBox;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel channelPanel;
    private javax.swing.ButtonGroup channelsRateGroup;
    private javax.swing.JButton defaultButton;
    private javax.swing.JRadioButton monoRadioButton;
    private javax.swing.JButton okButton;
    private javax.swing.JComboBox sampleRateComboBox;
    private javax.swing.JRadioButton stereoRadioButton;
    private javax.swing.JPanel volumePanel;
    private javax.swing.JSlider volumeSlider;
    // End of variables declaration//GEN-END:variables
}
